"""AWS CONSTANTS"""

AWS_SERVER_ACCESS_KEY = "AKIAYOEMXZI2CGWDLNHE"
AWS_SERVER_SECRET_KEY = "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"
INPUT_BUCKET_NAME = "pi-input-bucket"
OUTPUT_BUCKET_NAME = "pi-output-bucket"
RESULT_BUCKET_NAME = "pi-result-bucket"
REGION_NAME = "us-east-1"
TABLENAME = 'pi-student-table'



